# Site settings
title: szqtc's notebook
email: szqtclx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Share the knowledge I have learnt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://szqtc.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  szqtc
timezone: Asia/Shanghai


# Build settings
markdown: kramdown
